<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Londra Dil Okulu - 4 Hafta',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => 'dil-okulu',
                'country' => 'abd',
                'price' => '45000.00',
                'stock' => 20,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-18 23:54:46',
                'image' => 'products/default.webp',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Berlin Almanca Kursu - 8 Hafta',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '32000.00',
                'stock' => 15,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'New York İşletme Sertifikası',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => 'sertifika',
                'country' => 'abd',
                'price' => '85000.00',
                'stock' => 5,
                'image_path' => NULL,
                'is_active' => 0,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-18 23:43:01',
                'image' => 'products/default.webp',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Paris Sanat Eğitimi',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => 'sertifika',
                'country' => 'almanya',
                'price' => '55000.00',
                'stock' => 8,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-18 23:54:58',
                'image' => 'products/default.webp',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Roma Gastronomi Atölyesi',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => 'lisans',
                'country' => 'polonya',
                'price' => '28000.00',
                'stock' => 12,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-18 23:55:08',
                'image' => 'products/default.webp',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Dublin IT Staj Programı',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '38000.00',
                'stock' => 20,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Toronto Lise Değişim Programı',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => 'sertifika',
                'country' => 'abd',
                'price' => '120000.00',
                'stock' => 3,
                'image_path' => NULL,
                'is_active' => 0,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-18 23:29:16',
                'image' => 'products/default.webp',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Barcelona Tasarım Yaz Okulu',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '25000.00',
                'stock' => 18,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Viyana Klasik Müzik Eğitimi',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '42000.00',
                'stock' => 7,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Amsterdam Yazılım Kampı',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => 'sertifika',
                'country' => 'almanya',
                'price' => '65000.00',
                'stock' => 10,
                'image_path' => NULL,
                'is_active' => 0,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-18 23:43:16',
                'image' => 'products/default.webp',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Tokyo Japonca Hazırlık',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '50000.00',
                'stock' => 12,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Seul K-Pop Dans Akademisi',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '35000.00',
                'stock' => 25,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Sidney İngilizce ve Sörf Programı',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '48000.00',
                'stock' => 15,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Prag Mühendislik Stajı',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => 'lisans',
                'country' => 'almanya',
                'price' => '22000.00',
                'stock' => 30,
                'image_path' => NULL,
                'is_active' => 0,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-18 23:29:44',
                'image' => 'products/default.webp',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Zurich Finans Sertifika Programı',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '95000.00',
                'stock' => 4,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Madrid Spor Yönetimi Eğitimi',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '40000.00',
                'stock' => 10,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Lizbon Dijital Göçebe Eğitimi',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '15000.00',
                'stock' => 50,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Oslo Sürdürülebilir Enerji Kursu',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '58000.00',
                'stock' => 6,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Kopenhag Mimarlık Atölyesi',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '44000.00',
                'stock' => 9,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Budapeşte Tıp Hazırlık Programı',
                'description' => 'Global Vizyon ile hayallerine bir adım daha yaklaş. Bu program kapsamlı eğitim ve danışmanlık hizmetlerini içerir.',
                'category' => NULL,
                'country' => NULL,
                'price' => '30000.00',
                'stock' => 20,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 20:48:04',
                'updated_at' => '2026-05-16 20:48:04',
                'image' => 'products/default.webp',
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'testtt',
                'description' => 'kkk',
                'category' => 'lisans',
                'country' => 'abd',
                'price' => '4545.00',
                'stock' => 23,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-16 21:26:43',
                'updated_at' => '2026-05-31 17:53:43',
                'image' => 'products/CjxiZGBlvDoWnF7EF3wQBBjzOriaoIa781BBnrdR.jpg',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'lll',
                'description' => 'kkk',
                'category' => 'dil-okulu',
                'country' => 'ingiltere',
                'price' => '10.00',
                'stock' => 44,
                'image_path' => NULL,
                'is_active' => 0,
                'created_at' => '2026-05-16 22:09:39',
                'updated_at' => '2026-05-18 23:43:46',
                'image' => 'products/sdbCfqwciIDYZJY37lLIPOrSxoX9qqftCxVVzBSl.jpg',
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'ppp',
                'description' => 'pp',
                'category' => 'dil-okulu',
                'country' => 'polonya',
                'price' => '88.00',
                'stock' => 20,
                'image_path' => NULL,
                'is_active' => 1,
                'created_at' => '2026-05-18 23:55:30',
                'updated_at' => '2026-05-22 16:12:31',
                'image' => 'products/9PkWriL5OgzkqSVxyTzw2mBrdGIXc7qHATsn8WcN.jpg',
            ),
        ));
        
        
    }
}